version: "3.8"

services:
  nginx:
    container_name: dochub
    image: nginxinc/nginx-unprivileged:1.21-alpine
    volumes:
      - ./40-sed.sh:/docker-entrypoint.d/40-sed.sh
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      VUE_APP_PLANTUML_SERVER: localhost:8079/svg/
    ports:
      - "8080:8080"


 plantuml:
   image: ghcr.io/rabotaru/dochub/plantuml:v0.0.2
   container_name: plantuml
   ports:
     - "8079:8080"
